version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Web UI
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always

  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    env_file: ./auth_service/.env
    volumes:
      - ./auth_service:/app/data

  bot_service:
    build: ./bot_service
    container_name: bot_service
    network_mode: "host"
    command: python -m app.main
    env_file: ./bot_service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy

  celery_worker:
    build: ./bot_service
    container_name: celery_worker
    network_mode: "host"
    command: celery -A app.infra.celery_app worker --loglevel=info -P gevent --concurrency=10
    env_file: ./bot_service/.env
    depends_on:
      rabbitmq:
        condition: service_healthy